server:
  port: 9090
  servlet:
    context-path: /skeleton-loader
spring:
  datasource:
    url: jdbc:mysql://localhost/blog
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update